server:
  port: 8092

spring:
  application:
    name: serie-service

  zipkin:
    base-url: http://zipkin-service:9411/

  datasource:
    #    url: jdbc:mysql://database-service:3306/movie-service?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
    url: jdbc:mysql://localhost:3306/movie-service?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  config:
    import: optional:configserver:http://config-service:8888

eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/

queue:
  serie-service:
    name: SerieServiceQueue

message: Serie service is up

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Serie Service Application
  svc:
    port: ${server.port}